# 데이터베이스 설정하기
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@teacherdev09.kro.kr:8877:xe
spring.datasource.username=spring
spring.datasource.password=spring

#hikariCP 설정하기
spring.datasource.hikari.pool-name=jk-pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=1800000
spring.datasource.hikari.max-lifetime=1800000

# mybatis 연결하기
mybatis.config-location=classpath:mybatis/config/mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mappers/**/*.xml

spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:initdata/schema/schema.sql
spring.sql.init.data-locations=classpath:initdata/data/data.sql

# hibernate 설정하기
spring.jpa.database=oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
