spring.application.name=basicboot
# 서버포트 설정하기
#server.port=9090
# 서버인코딩 설정하기
server.servlet.encoding.charset=utf-8

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 다른 프로퍼티파일 불어와서 적용하기
spring.config.import=properties/datasource.properties, properties/log.properties

# 실행하는 프로퍼티파일 지정하기 (파일을 만들어서 포트번호 주소를 달리할 수 있다. =dev, =prop)
spring.profiles.active=prop

# 내 클래스가 필요한 데이터 설정하기
linux.home=/home/ubuntu
linux.ip=56.123.64.11
linux.port=1234

env.javahome=${JAVA_HOME:123456}
env.path=${path}
env.userkey=${userkey:1234sgdmgspglkhk}

app.bs.name=bslove
app.bs.ip=12.123.45.11
app.bs.port=8888
app.bs.security.token=A2423FD34
app.bs.security.role=USER,ADMIN